[project]
name = "irsh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matrix-nio>=0.25.2",
    "slackclient>=2.9.4",
]
